<?php

namespace Ebay\Common;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-05-27 at 16:04:25.
 */
class CurlTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Curl
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Curl;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Ebay\Common\Curl::setOption
     * @todo   Implement testSetOption().
     */
    public function testSetOption() {
        $this->assertTrue($this->object->setOption(CURLOPT_AUTOREFERER, true));
    }

    /**
     * @covers Ebay\Common\Curl::setOptionArray
     * @todo   Implement testSetOptionArray().
     */
    public function testSetOptionArray() {
        
        $options = array(
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_HEADER => true
        );
 
        $this->assertTrue($this->object->setOptionArray($options));
    }

    /**
     * @covers Ebay\Common\Curl::send
     * @todo   Implement testSend().
     */
    public function testSend() {
        
        // Setup Endpoint
        //$this->object->setOption(CURLOPT_URL, 'www.google.com');
        
        //$this->assertTrue($this->object->send());
    }

    /**
     * @covers Ebay\Common\Curl::getResponse
     * @todo   Implement testGetResponse().
     */
    public function testGetResponse() {
        
        $reflection = new \ReflectionClass($this->object);
 
        $reflection_property = $reflection->getProperty('response');
        $reflection_property->setAccessible(true);
        $reflection_property->setValue($this->object,"Response body");
 
        $this->assertEquals("Response body",$this->object->getResponse());
    }

    /**
     * @covers Ebay\Common\Curl::getError
     * @todo   Implement testGetError().
     */
    public function testGetError() {
        
        $reflection = new \ReflectionClass($this->object);
 
        $reflection_property = $reflection->getProperty('error');
        $reflection_property->setAccessible(true);
        $reflection_property->setValue($this->object, array(
            'number' => 1,
            'message' => 'Test error message'
        ));
        
        $error = $this->object->getError();
        
        $this->assertArrayHasKey('number',$error);
        $this->assertEquals(1,$error['number']);    
        
        $this->assertArrayHasKey('message',$error);
        $this->assertEquals('Test error message',$error['message']);
        
    }

    /**
     * @covers Ebay\Common\Curl::getInformation
     * @todo   Implement testGetInformation().
     */
    public function testGetInformation() {
        
        $reflection = new \ReflectionClass($this->object);
 
        $reflection_property = $reflection->getProperty('information');
        $reflection_property->setAccessible(true);
        $reflection_property->setValue($this->object, array(
            'key1' => 1,
            'key2' => 'Test error message'
        ));
        
        $information = $this->object->getInformation();
        
        $this->assertArrayHasKey('key1',$information);
        $this->assertEquals(1,$information['key1']);       
        
        $this->assertArrayHasKey('key2',$information);
        $this->assertEquals('Test error message',$information['key2']);
    }

}
